Repository ECE651-Group-15/backend, pull requests merged in 2024-02, with the labels that each got.

#51 Be 17: Add get posted listing by page function
  src/main/java/domain/listing/ListingService.java
  src/main/java/domain/listing/PostedListingPage.java
  src/main/java/infrastructure/CustomerProfileResources.java
  src/main/java/infrastructure/ListingAndCustomerResources.java
  src/main/java/infrastructure/dto/in/profile/GetCustomerPostedListingsDto.java
  src/main/java/infrastructure/dto/out/listing/ListingPageDto.java
  src/main/java/infrastructure/dto/out/listing/PostedListingPageDto.java
Labels: task / user story

#52 Be 18: Add get all listings endpoint.
  src/main/java/domain/listing/ListingRepository.java
  src/main/java/domain/listing/ListingService.java
  src/main/java/domain/listing/ListingWithCustomerInfo.java
  src/main/java/infrastructure/CustomerListingResources.java
  src/main/java/infrastructure/dto/in/listing/ListingPageDto.java
  src/main/java/infrastructure/dto/in/profile/GetCustomerPostedListingsDto.java
  src/main/java/infrastructure/dto/out/ListingAndCustomerDto.java
  src/main/java/infrastructure/dto/out/listing/ListingPageDetailsDto.java
  src/main/java/infrastructure/dto/out/listing/ListingWithCustomerInfoDto.java
  src/main/java/infrastructure/sql/PanacheListingRepository.java
Labels: task / user story

#53 Be 19: Add endpoint to get all my starred listings
  postgreSQL_setup.md
  src/main/java/infrastructure/CustomerListingResources.java
  src/main/java/infrastructure/dto/in/profile/GetCustomerListingsDto.java
  src/main/java/infrastructure/dto/in/profile/GetCustomerPostedListingsDto.java
  src/main/java/infrastructure/dto/out/listing/StarredListingPageDto.java
Labels: task / user story

#59 BE-37: fixed the domain method, when FE not passing long and lat, NPE was thrown
  src/main/java/infrastructure/sql/entity/CustomerProfileEntity.java
  src/main/resources/application.properties
Labels: bug

#62 Be 38: Add avatar to profile related dto, also add get all profiles endpoint
  src/main/java/domain/MD5Util.java
  src/main/java/domain/listing/Category.java
  src/main/java/domain/listing/ListingPage.java
  src/main/java/domain/profile/CustomerProfile.java
  src/main/java/domain/profile/CustomerProfileRepository.java
  src/main/java/domain/profile/CustomerProfileService.java
  src/main/java/infrastructure/CustomerListingResources.java
  src/main/java/infrastructure/CustomerProfileResources.java
  src/main/java/infrastructure/dto/in/listing/PageDto.java
  src/main/java/infrastructure/dto/out/profile/CustomerProfilePageDto.java
  src/main/java/infrastructure/dto/out/profile/CustomerProfilesDetailsDto.java
  src/main/java/infrastructure/sql/PanacheCustomerProfileRepository.java
  src/main/java/infrastructure/sql/PanacheListingRepository.java
  src/main/java/infrastructure/sql/entity/CustomerProfileEntity.java
  src/main/resources/application.properties
Labels: task / user story

#63 BE-24: Add integration test for create listing
  pom.xml
  src/main/java/infrastructure/CustomerProfileResources.java
  src/main/java/infrastructure/dto/out/profile/CustomerProfilePageDto.java
  src/main/java/infrastructure/dto/serialization/ClientErrorMapper.java
  src/main/java/infrastructure/dto/serialization/DeserializationErrorMapper.java
  src/main/java/infrastructure/dto/serialization/RuntimeExceptionMapper.java
  src/test/java/infrastructure/ListingResourceTest.java
  src/test/java/infrastructure/ListingResourcesIT.java
Labels: test

#64 BE-39: Add CI/CD for main branch
  .github/workflows/cicd.yml
  deploy_script.sh
Labels: enhancement

#67 BE-25: Added integration tests for get-listing
  src/test/java/infrastructure/ListingResourcesIT.java
Labels: test

#69 BE-41: fix the issue for update listing and update profile
  src/main/java/domain/listing/ListingRepository.java
  src/main/java/domain/listing/ListingService.java
  src/main/java/domain/profile/CustomerProfileRepository.java
  src/main/java/domain/profile/CustomerProfileService.java
  src/main/java/domain/profile/UpdateCustomerProfile.java
  src/main/java/infrastructure/CustomerProfileResources.java
  src/main/java/infrastructure/ListingResources.java
  src/main/java/infrastructure/dto/in/profile/UpdateCustomerProfileDto.java
  src/main/java/infrastructure/result/UpdateCustomerProfileResult.java
  src/main/java/infrastructure/result/UpdateListingResult.java
  src/main/java/infrastructure/sql/PanacheCustomerProfileRepository.java
  src/main/java/infrastructure/sql/PanacheListingRepository.java
  src/main/java/infrastructure/sql/entity/CustomerProfileEntity.java
  src/main/java/infrastructure/sql/entity/ListingEntity.java
  src/test/java/domain/listing/ListingServiceTest.java
Labels: bug

#72 BE-43: fix the IT issue
  src/test/java/infrastructure/ListingResourcesIT.java
Labels: bug

#76 BE-33: add IT for create customer profile
  src/test/java/infrastructure/CustomerProfileResourcesIT.java
  src/test/java/infrastructure/ListingResourcesIT.java
Labels: test

#81 Be 45: Update error message for star listing page exception
  src/main/java/domain/listing/ListingService.java
  src/main/java/domain/profile/CustomerProfileService.java
  src/main/java/infrastructure/CustomerListingResources.java
  src/main/java/infrastructure/result/CustomerStarListingResult.java
  src/main/java/infrastructure/result/ListingStarListingResult.java
  src/test/java/domain/listing/ListingServiceTest.java
  src/test/java/infrastructure/CustomerProfileResourcesIT.java
Labels: bug

#83 BE-28: Added IT for starlisting, modified with BE-45, and added IT for getCustomerPostedListings
  src/test/java/infrastructure/CustomerListingResourcesIT.java
  src/test/java/infrastructure/ListingResourcesIT.java
Labels: test

#88 Be 44: Add unstar endpoint
  src/main/java/domain/listing/ListingService.java
  src/main/java/domain/profile/CustomerProfileService.java
  src/main/java/infrastructure/CustomerListingResources.java
  src/main/java/infrastructure/result/CustomerStarResult.java
  src/main/java/infrastructure/result/CustomerUnStarResult.java
  src/main/java/infrastructure/result/ListingStarResult.java
  src/main/java/infrastructure/result/ListingUnStarResult.java
  src/main/java/infrastructure/sql/PanacheListingRepository.java
  src/test/java/domain/listing/ListingServiceTest.java
  src/test/java/infrastructure/CustomerListingResourcesIT.java
  src/test/java/infrastructure/CustomerListingResourcesMockIT.java
Labels: task / user story

#89 BE-23: Added IT for CustomerProfileService
  src/main/java/domain/profile/CreateCustomerProfile.java
  src/main/java/domain/profile/CustomerProfileService.java
  src/test/java/domain/profile/CustomerProfileServiceTest.java
  src/test/java/infrastructure/CustomerListingResourcesIT.java
  src/test/java/infrastructure/CustomerProfileResourcesIT.java
Labels: test

#92 BE-46: Add login endpoint
  src/main/java/domain/profile/CustomerProfileService.java
  src/main/java/domain/profile/Login.java
  src/main/java/infrastructure/CustomerProfileResources.java
  src/main/java/infrastructure/dto/in/profile/LoginDto.java
  src/main/java/infrastructure/sql/PanacheCustomerProfileRepository.java
Labels: task / user story

#94 BE 47 Add integration test for login endpoint
  src/test/java/domain/profile/CustomerProfileServiceTest.java
Labels: test
